apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: techcommerce
stringData:
  # examples
  PRODUCT_DB_URI: postgresql://user:pass@db:5432/products
  ORDER_DB_URI: postgresql://user:pass@db:5432/orders